<?php

// Require the files from this one so when implementing just need to call this single file
require_once __DIR__ . '/../vendor/phpMailer/Exception.php';
require_once __DIR__ . '/../vendor/phpMailer/PHPMailer.php';
require_once __DIR__ . '/../vendor/phpMailer/SMTP.php';
require_once __DIR__ . '/../database/Config.php';

use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

class MailService{

  function SendMail($recipient, $subject, $body, $altBody = 'Autogenerated mail.'){
    try {
      
      $mail = new PHPMailer(true);

      // Mailer configuration
      $mail->SMTPDebug = 2;
      $mail->isSMTP();
      $mail->Host = 'smtp.gmail.com';
      $mail->SMTPAuth = true;
      $mail->Username = MAIL_HOST; //paste one generated by Mailtrap
      $mail->Password = MAIL_PWD; //paste one generated by Mailtrap
      $mail->SMTPSecure = 'tls';
      $mail->Port = 587;

      // Sender
      $mail->setFrom('caralibro@autoservice.com', 'CaraLibro', false);

      // Recipient
      $mail->addAddress($recipient);

      // Content
      $mail->isHTML(true);
      $mail->Subject = $subject; 
      $mail->Body = $body; 
      $mail->AltBody = $altBody; 
      $result = $mail->send(); 

      // Validate mailing result
      if($result){
        echo 'Message has been sent';
      }else{
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
      }

    } catch (Exception $e) {

      // Capture any other unexpected exception
      echo 'Mailer Error: ' . $e->getMessage();
      echo 'Mailer Error: ' . $mail->ErrorInfo;
    }
  }
}